# Generated by Django 2.2.5 on 2019-09-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('covering', models.CharField(max_length=100)),
                ('train_date', models.DateTimeField(verbose_name='Date Trained')),
                ('score', models.DecimalField(decimal_places=3, max_digits=19)),
                ('source', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name='Date asked')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceLoader.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceLoader.Stream')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceLoader.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_gen', models.CharField(choices=[('Y', 'Useful'), ('N', 'Not useful'), ('-', 'Provide no feedback')], default='-', max_length=1)),
                ('feedback_det', models.CharField(max_length=2000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceLoader.Question')),
            ],
        ),
    ]
