# Generated by Django 2.2.5 on 2019-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
