# Generated by Django 2.2.5 on 2019-09-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0002_conference_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='is_default',
        ),
    ]
