# Generated by Django 2.2.5 on 2019-09-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0003_remove_conference_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTeamConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceLoader.Conference')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceLoader.Team')),
            ],
        ),
    ]
