# Generated by Django 2.2.5 on 2020-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0004_defaultteamconference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='default question', max_length=500),
        ),
    ]
