# Generated by Django 2.2.5 on 2020-02-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0006_auto_20200203_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_gen',
            field=models.CharField(choices=[('Y', 'Useful'), ('N', 'Not useful')], max_length=1),
        ),
    ]
