# Generated by Django 2.2.5 on 2020-02-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0007_auto_20200203_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_gen',
        ),
    ]
