# Generated by Django 2.2.5 on 2020-03-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0008_remove_feedback_feedback_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
    ]
