# Generated by Django 2.2.5 on 2020-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0010_auto_20200301_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
