# Generated by Django 2.2.5 on 2020-03-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceLoader', '0011_person_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slack_id',
            field=models.CharField(default='', max_length=12),
        ),
    ]
